version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
  
  backend:
    build: ./backend
    environment:
      - DB_HOST=postgres
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_PORT=5432  # Specify the port here
    ports:
      - "5000:3000"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_PORT=5432  # Specify the port here
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

