name: Frontend Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials from IAM role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
          aws-region: sa-east-1 

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Deploy to S3 and Invalidate CloudFront
        run: |
          aws s3 sync ./dist s3://test-paulovitor-frontend --delete
          aws cloudfront create-invalidation --distribution-id your-cloudfront-distribution-id --paths "/*"

      # Additional steps as needed for your frontend build and deployment process

